spring:
  # database
  datasource:
    url: jdbc:postgresql://ec2-54-159-22-90.compute-1.amazonaws.com:5432/ddi1o6vilfp7tg
    username: qytqnhuinsxveb
    password: e7c8fd7ce8f147f9fffd5c8e4c9e1c939ededd3e0245607fa907454193670901

  # jpa
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10DialectDialect
    hibernate:
      ddl-auto: update

